//? hotFood , coldFood , hotDrink , coldDrink , edible

const products = [
	{
		id: 1,
		group: 'hotFood',
		title: 'ساندویچ همبرگر',
		image: '/images/3.jpg',
		price: 40_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 2,
		group: 'coldFood',
		title: 'ساندویچ کالباس',
		image: '/images/3.jpg',
		price: 30_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 3,
		group: 'hotDrink',
		title: 'چای',
		image: '/images/2.jpg',
		price: 20_000,
		isDiscount: true,
		oldPrice: 30_000,
	},
	{
		id: 4,
		group: 'coldDrink',
		title: 'نوشابه کوکاکولا',
		image: '/images/1.jpg',
		price: 10_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 5,
		group: 'edible',
		title: 'کیک تاینی',
		image: '/images/2.jpg',
		price: 5_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 6,
		group: 'coldFood',
		title: 'اسنک نوتلا',
		image: '/images/3.jpg',
		price: 10_000,
		isDiscount: true,
		oldPrice: 100_000,
	},
	{
		id: 7,
		group: 'hotFood',
		title: 'ساندویچ ماکارانی',
		image: '/images/4.jpg',
		price: 50_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 8,
		group: 'coldDrink',
		title: 'ماالشعیر جو',
		image: '/images/1.jpg',
		price: 60_000,
		isDiscount: false,
		oldPrice: null,
	},
]

export default products;