//? hotFood , coldFood , hotDrink , coldDrink , edible

const products = [
	{
		id: 1,
		group: 'hotFood',
		title: 'یوسف سرد',
		image: '/images/3.jpg',
		price: 40_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 2,
		group: 'coldFood',
		title: 'یوسف گرم',
		image: '/images/3.jpg',
		price: 30_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 3,
		group: 'hotDrink',
		title: 'یوسف ۱',
		image: '/images/2.jpg',
		price: 20_000,
		isDiscount: true,
		oldPrice: 30_000,
	},
	{
		id: 4,
		group: 'coldDrink',
		title: 'یوسف ۲',
		image: '/images/1.jpg',
		price: 10_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 5,
		group: 'edible',
		title: 'یوسف ۳',
		image: '/images/2.jpg',
		price: 5_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 6,
		group: 'coldFood',
		title: 'یوسف دنده به دنده',
		image: '/images/3.jpg',
		price: 10_000,
		isDiscount: true,
		oldPrice: 100_000,
	},
	{
		id: 7,
		group: 'hotFood',
		title: 'یوسف بشقاب پرنده',
		image: '/images/4.jpg',
		price: 50_000,
		isDiscount: false,
		oldPrice: null,
	},
	{
		id: 8,
		group: 'coldDrink',
		title: 'یوسف چرا نمیخنده',
		image: '/images/1.jpg',
		price: 60_000,
		isDiscount: false,
		oldPrice: null,
	},
]

export default products;